export const STATUS = {
  READY_FOR_QUOTE: 'Ready For Quote',
  QUOTED: 'Quoted',
  INVOICED: 'Invoiced',
  BOOKING: 'Booking',
  BOOKED: 'Booked',
  BOOKING_FAILED: 'Booking Failed',
  ERROR: 'Error',
  TRIANGLE: 'Manual - Triangle',
  PENDING_FINANCE_APPROVAL: 'Pending Finance Approval',
  AWAITING_RETURN: 'Awaiting Return',
  CONDITION_CHECKED: 'Condition Checked',
}

let _nextId = 1
const id = () => _nextId++

export const mockOrders = [
  {
    id: id(), rowIndex: 2,
    dateReceived: '2026-05-29T09:15:00',
    status: STATUS.INVOICED,
    psNo: '2-24528', psUrl: '#',
    invoiceUrl: 'https://drive.google.com/file/d/EXAMPLE/view', invoiceNo: '11-81188',
    customer: { company: 'My Glass Mosselbay', contact: 'Micaela', phone: '075 044 6859', email: 'micaelav@myglass.co.za' },
    address: { street: '17 Via Appie Street', suburb: 'Voorbaai', city: 'Mossel Bay', province: 'Western Cape', postalCode: '6500' },
    items: [
      { sku: '108712T', h: 3, w: 123, l: 106, kg: 13, qty: 1 },
      { sku: '108779', h: 86, w: 12, l: 95, kg: 15.9, qty: 1 },
    ],
    tcgQuote: 271.40, epxQuote: 318.00,
    selectedCourier: 'TCG', approved: false, buyLabel: false,
    waybillNo: '', waybillLink: '', epxLabels: '', errorMessage: '',
  },
  {
    id: id(), rowIndex: 3,
    dateReceived: '2026-05-29T08:30:00',
    status: STATUS.QUOTED,
    psNo: '2-24536', psUrl: '#',
    customer: { company: 'Windscreen Pro', contact: 'Johan', phone: '067 769 4244', email: 'johan@windscreenpro.co.za' },
    address: { street: '42 Industrial Road', suburb: 'Stikland', city: 'Bellville', province: 'Western Cape', postalCode: '7530' },
    items: [
      { sku: '118604', h: 6, w: 145, l: 98, kg: 19.2, qty: 1 },
      { sku: '118604R', h: 6, w: 145, l: 98, kg: 2.1, qty: 1 },
    ],
    tcgQuote: 189.50, epxQuote: 205.00,
    selectedCourier: 'EPX', approved: true, buyLabel: false,
    waybillNo: '', waybillLink: '', epxLabels: '', errorMessage: '',
  },
  {
    id: id(), rowIndex: 4,
    dateReceived: '2026-05-29T10:02:00',
    status: STATUS.READY_FOR_QUOTE,
    psNo: '2-24541', psUrl: '#',
    customer: { company: 'Boksburg Auto Glass', contact: 'Thabo', phone: '011 823 4455', email: 'thabo@bauto.co.za' },
    address: { street: '15 Rondebult Road', suburb: 'Boksburg North', city: 'Boksburg', province: 'Gauteng', postalCode: '1460' },
    items: [
      { sku: '134127', h: 97, w: 3, l: 144, kg: 17, qty: 1 },
    ],
    tcgQuote: null, epxQuote: null,
    selectedCourier: '', approved: false, buyLabel: false,
    waybillNo: '', waybillLink: '', epxLabels: '', errorMessage: '',
  },
  {
    id: id(), rowIndex: 5,
    dateReceived: '2026-05-29T10:45:00',
    status: STATUS.READY_FOR_QUOTE,
    psNo: '2-24542', psUrl: '#',
    customer: { company: 'Pretoria Glass Centre', contact: 'Annelie', phone: '012 344 7821', email: 'annelie@ptoglass.co.za' },
    address: { street: '8 Nettleton Street', suburb: 'Gezina', city: 'Pretoria', province: 'Gauteng', postalCode: '0084' },
    items: [
      { sku: '109001', h: 40, w: 3, l: 50, kg: 2.3, qty: 2 },
      { sku: '124620', h: 95.5, w: 12, l: 118, kg: 22.5, qty: 1 },
    ],
    tcgQuote: null, epxQuote: null,
    selectedCourier: '', approved: false, buyLabel: false,
    waybillNo: '', waybillLink: '', epxLabels: '', errorMessage: '',
  },
  {
    id: id(), rowIndex: 6,
    dateReceived: '2026-05-29T07:55:00',
    status: STATUS.BOOKING,
    psNo: '2-24537', psUrl: '#',
    customer: { company: 'Ugie Mac Quarry', contact: 'Pieter', phone: '039 966 0011', email: 'pieter@ugiemac.co.za' },
    address: { street: '1 Quarry Lane', suburb: 'Industrial', city: 'Ugie', province: 'Eastern Cape', postalCode: '5470' },
    items: [
      { sku: '100396', h: 95, w: 12, l: 145, kg: 21.9, qty: 1 },
    ],
    tcgQuote: 445.00, epxQuote: 398.50,
    selectedCourier: 'TCG', approved: true, buyLabel: true,
    waybillNo: '', waybillLink: '', epxLabels: '', errorMessage: '',
  },
  {
    id: id(), rowIndex: 7,
    dateReceived: '2026-05-29T11:20:00',
    status: STATUS.QUOTED,
    psNo: '2-24539', psUrl: '#',
    customer: { company: 'PEX Hydraulics Springbok (Pty) Ltd', contact: 'Jonathan', phone: '027 712 3344', email: 'jonathan@pexhydraulics.co.za' },
    address: { street: '3 Van Riebeeck Street', suburb: '', city: 'Springbok', province: 'Northern Cape', postalCode: '8240' },
    items: [
      { sku: '118901', h: 5, w: 88, l: 112, kg: 11.4, qty: 1 },
    ],
    tcgQuote: 512.00, epxQuote: 487.00,
    selectedCourier: 'EPX', approved: true, buyLabel: true,
    waybillNo: '', waybillLink: '', epxLabels: '', errorMessage: '',
  },
  {
    id: id(), rowIndex: 8,
    dateReceived: '2026-05-29T06:30:00',
    status: STATUS.ERROR,
    psNo: '2-24538', psUrl: '#',
    customer: { company: 'SIMO Rigging Solutions (Pty) Ltd', contact: 'Simon', phone: '031 569 8800', email: 'simon@simorigging.co.za' },
    address: { street: '22 Brickfield Road', suburb: 'Jacobs', city: 'Durban', province: 'KwaZulu-Natal', postalCode: '4052' },
    items: [],
    tcgQuote: null, epxQuote: null,
    selectedCourier: '', approved: false, buyLabel: false,
    waybillNo: '', waybillLink: '', epxLabels: '',
    errorMessage: 'SKU TI6-8: qty=1 has Qty Allocated = 0. SKU 108779: qty=86 matches a dimension value — OCR column mis-read: High was probably read as Qty Allocated.',
  },
  {
    id: id(), rowIndex: 9,
    dateReceived: '2026-05-29T08:10:00',
    status: STATUS.TRIANGLE,
    psNo: '2-24540', psUrl: '#',
    customer: { company: 'Triangle Distribution', contact: 'Mpho', phone: '011 444 9900', email: 'mpho@triangle.co.za' },
    address: { street: '88 Heidelberg Road', suburb: 'Alberton North', city: 'Alberton', province: 'Gauteng', postalCode: '1449' },
    items: [
      { sku: '122015', h: 4, w: 160, l: 200, kg: 35.0, qty: 3 },
    ],
    tcgQuote: null, epxQuote: null,
    selectedCourier: 'Triangle', approved: false, buyLabel: false,
    waybillNo: '', waybillLink: '', epxLabels: '', errorMessage: '',
  },
  {
    id: id(), rowIndex: 10,
    dateReceived: '2026-05-28T14:55:00',
    status: STATUS.BOOKING_FAILED,
    psNo: '2-24535', psUrl: '#',
    customer: { company: 'PG Glass Bedfordview', contact: 'Emme', phone: '076 438 2961', email: '' },
    address: { street: '21 Bradford Road', suburb: 'Bedfordview', city: 'Germiston', province: 'Gauteng', postalCode: '2008' },
    items: [
      { sku: '108712T', h: 3, w: 123, l: 106, kg: 13, qty: 1 },
    ],
    tcgQuote: 298.00, epxQuote: null,
    selectedCourier: 'TCG', approved: true, buyLabel: true,
    waybillNo: '', waybillLink: '', epxLabels: '',
    errorMessage: 'Booking failed: service_level_code ECOR not available for this lane. Tried ECO, ECOR.',
  },
]

export const mockHistory = [
  {
    id: id(), rowIndex: 101,
    dateReceived: '2026-05-28T15:33:00',
    status: STATUS.BOOKED,
    psNo: '2-24520', psUrl: '#',
    customer: { company: 'CTC Plant Company Pty Ltd', contact: 'Roy Heather', phone: '061 421 9184', email: 'jcbparts@ctcplant.co.za' },
    address: { street: 'Cnr. Michigan & Manchester St', suburb: 'Boquinar Industrial', city: 'Epping Industrial Area', province: 'Western Cape', postalCode: '7460' },
    items: [{ sku: '124620', h: 95.5, w: 12, l: 118, kg: 22.5, qty: 1 }],
    tcgQuote: 519.20, epxQuote: 318.00,
    selectedCourier: 'EPX', approved: true, buyLabel: true,
    waybillNo: 'GCO6157654', waybillLink: '#', epxLabels: '#', errorMessage: '',
  },
  {
    id: id(), rowIndex: 102,
    dateReceived: '2026-05-28T14:30:00',
    status: STATUS.BOOKED,
    psNo: '2-24519', psUrl: '#',
    customer: { company: 'RET', contact: 'Bart', phone: '082 896 3161', email: '' },
    address: { street: '68 Brendar Rd', suburb: '', city: 'Bloemfontein', province: 'Free State', postalCode: '9300' },
    items: [{ sku: '109001', h: 40, w: 3, l: 50, kg: 2.3, qty: 1 }],
    tcgQuote: 135.70, epxQuote: 262.40,
    selectedCourier: 'TCG', approved: true, buyLabel: true,
    waybillNo: 'XFGTFK', waybillLink: '#', epxLabels: '', errorMessage: '',
  },
  {
    id: id(), rowIndex: 103,
    dateReceived: '2026-05-28T15:39:00',
    status: STATUS.BOOKED,
    psNo: '2-24488', psUrl: '#',
    customer: { company: 'Get Spares', contact: '', phone: '067 769 4244', email: '' },
    address: { street: '13 Steventon Road', suburb: 'Anderbolt', city: 'Boksburg', province: 'Gauteng', postalCode: '1482' },
    items: [{ sku: '134127', h: 97, w: 3, l: 144, kg: 17, qty: 1 }],
    tcgQuote: 271.40, epxQuote: 414.66,
    selectedCourier: 'TCG', approved: true, buyLabel: true,
    waybillNo: 'WKNS8Q', waybillLink: '#', epxLabels: '', errorMessage: '',
  },
]
